
name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/ruff-action@v4.0.0
      - run: ruff check --diff
      - run: ruff format --diff --check

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v6

      - run: python -c "import sys; print(sys.version)"
      - run: uv pip install -e . --system
      - run: python -m unittest -v tests/test_zeekpy.py
